name: photo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  dio: ^5.7.0
  cupertino_icons: ^1.0.8
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
