name: photo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # Svg support:
  flutter_svg: ^2.0.17
  # Annotations for build_runner to run json_serializable tasks
  json_annotation: ^4.9.0
  # Router
  go_router: ^14.1.0
  # Network
  dio: ^5.7.0
  logger: ^2.5.0
  # State:
  flutter_bloc: ^9.0.0
  # Upload images for mobile:
  image_picker: ^1.0.7
  # Upload images for web:
  file_picker: ^6.1.1
  # Window manager for desktop:
  window_manager: ^0.4.3
  desktop_window: ^0.4.2
  
  equatable: ^2.0.5

  dartz: ^0.10.1
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Generate fromJson/toJson
  json_serializable: ^6.9.0
  # Build runner for code_gen
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/

scripts:
  start: flutter run -d chrome --web-port 8080
